### ISSUE TITLE
Update bounty details page

### ISSUE THREAD

**Issue by GTChase** [gitcoinco/web#10476]
**User Story:**
As a contributor 
I want to see the fields from the bounty creation worfklow
So that i receive the value of the fields that were added to understand the scope of a bounty completley

**Acceptance Criteria**
GIVEN I have deployed the new bounty creation workflow
WHEN I click into ANY bounty to see its details
THEN I should see the following new fields as then:
- Contact information - i.e. discord name, telgram handle, or email
- Submission cut off date
- Estimated payout date
- Type of bounty - Traditional or multiple
- Acceptance criteria and resources
- Bounty owner(s)

**Product & Design Links:**

**Tech Details:**

**Open Questions:**
How do we want to handle bounties that already exist?

**Comment by GTChase** [comment]
I cannot test this currently because i cannot load the bounty explorer at all.. 
![Screen Shot 2022-04-26 at 5 13 45 PM](https://user-images.githubusercontent.com/95642312/165393432-43af0d83-5e3b-4a9b-9da3-7b0bc1ce87d1.png)

@nutrina

**Comment by GTChase** [comment]
Looks like a couple of display issues on the date fields here..

This bounty had a estimated apyout date on the default date 30 days from now and it is showing 265 years from now lol. 

Also this bounty was set to never expire and we agreed to not show that field if it is set to never expire.
![Screen Shot 2022-04-28 at 3 45 40 PM](https://user-images.githubusercontent.com/95642312/165833472-f418ea44-1811-4c8e-88f6-90382582d1ed.png)

cc. @nutrina

**Comment by nutrina** [comment]
This is fixed

**Comment by willsputra** [comment]
hmm im still seeing the same issue with a bounty that never expires
<img width="723" alt="image" src="https://user-images.githubusercontent.com/19514207/166495916-181c2500-7b18-4468-92a3-2446bbc4c68f.png">

http://gitcoin-review-10409-a81235f-1873182368.us-west-2.elb.amazonaws.com/issue/5

**Comment by GTChase** [comment]
@nutrina - i am seeing the same issue as Will.. We should not be showing Estimated Payout Date if it sets to never expire.. 

That poses the question of what to do with submission cutoff date if its never expiring? @willsputra what do you think?

**Comment by nutrina** [comment]
When "Never expires" is checked for the bounty when created, then in the details page we should also display "Never expires"

**Comment by nutrina** [comment]
Fix is made (have adde field `never_expires` in the DB.
Deployment is on the way

**Comment by GTChase** [comment]
The above looks good, just the same issues mentioned on the preview story. 

Looks like the dates for submission cut off date and estimated payout date are broken again.. I have both set to a month from today and when you go to preview page, both are showing as 3 months away. This issue persists on the details page as well. 

![Screen Shot 2022-05-09 at 10 57 24 AM](https://user-images.githubusercontent.com/95642312/167437881-84efde0f-e8cb-4ac5-bd86-165a7066a8ab.png)
![Screen Shot 2022-05-09 at 10 57 34 AM](https://user-images.githubusercontent.com/95642312/167437912-332c4913-8c10-4d70-a3bd-1ac36ec2c0d7.png)



When set to never expires, all looks well.. 
cc. @nutrina

**Comment by willsputra** [comment]
same comment on preview story too:

Looks like it's fixed? tried out two weeks and 1 year and it looks fine
http://gitcoin-review-10409-a81235f-1873182368.us-west-2.elb.amazonaws.com/issue/16

lgtm!
