### ISSUE TITLE
Faied to get my own ens : oussema.gitcoin.eth

### ISSUE THREAD

**Issue by oussema** [gitcoinco/web#6053]
Why I can't get my own ens ? I followed this blog https://gitcoin.co/blog/personalize-your-own-gitcoin-ens-name/ I sign with my metamsk wallet but it doesn't work. Any one face the same problem ?

**Comment by zoek1** [comment]
Yep,  the moment.js library is missing. Today I'll submit a patch to solve this 🙂

**Comment by oussema** [comment]
I'm not sure that the problem was fixed

**Comment by developerfred** [comment]
Hi @oussema the problem still persists.
<img width="1200" alt="Captura de Tela 2020-02-29 às 18 44 55" src="https://user-images.githubusercontent.com/57037080/75615545-ba8ce400-5b23-11ea-83eb-35ff1fdd27d4.png">

**Comment by williamchong007** [comment]
![image](https://user-images.githubusercontent.com/6198816/78340275-62d11500-75c8-11ea-9aaf-ea5c18c39b70.png)
Is this issue fixed yet? Currently I am getting HTTP ERROR 500 after signing with metamask
