### ISSUE TITLE
Getting an Error When Trying to Tip User

### ISSUE THREAD

**Issue by mkosowsk** [gitcoinco/web#776]
### Pre-condition

0. Via Metamask, be connected to the Main Ethereum Network

### Steps to Reproduce
0. Navigate to someone's Github profile and click the Tip User Button.
1. Fill out the Amount of ETH. I am trying with 0.0001
2. Agree to ToS and sent tip (or fill out info in Advanced, seeing same error for both Simple and Advanced)

![gitcoin co_tip_send_2_](https://user-images.githubusercontent.com/7970539/38247089-02eb9012-3712-11e8-861b-c93944a99ec3.png)

### Expected Behavior
0. Tip goes through correctly and recipient lavishes praise upon me for giving them ETH.

### Actual Behavior
0. Encounters this error.

<img width="1470" alt="screen shot 2018-04-03 at 7 38 06 am" src="https://user-images.githubusercontent.com/7970539/38247104-0d70df4c-3712-11e8-8e39-cdbd5b09ee4d.png">

@vs77bb @mbeacom do you see this error?

**Comment by owocki** [comment]
do you get the Accounts errror on pageload and the 'txParams' error upon click?  or are both errors upon click?

**Comment by owocki** [comment]
51a4c529d2958a0be9bdb099fe8058d1e6a30232 should fix this. . wanna retry Mitch?

**Comment by owocki** [comment]
10000000 ETH, send it to kevinowocki.eth

**Comment by mkosowsk** [comment]
Unforunately still seeing the error :( looks like our old friend Vivek is gonna die penniless in the gutter 😭

I may be reading the error wrong but if it's complaining that gasLimit in txParams is not a string wouldn't we want to go the other way from `parseInt` and instead do something like

`var _gasLimit = String(_gas * 1.01);`

or

`var _gasLimit =(_gas * 1.01) + "";`

or whatever other BS that JavaScript accepts? 😂

If `parseInt` functionality is what we're after, we may have to try to use `Number()` instead per [this StackOverflow](https://stackoverflow.com/a/4090577)

Is it working on your end?

**Comment by mkosowsk** [comment]
@owocki Let me know if you've got a bit of time to hop on a Zoom, would like to resolve this (either on my end or for Gitcoin at large) as it's blocking launch of my baby #760 👍🏻

**Comment by owocki** [comment]
yeah its working on my end.. which is why its all the more strange im not seeing the same error as you

just deployed e82624d2a905109be30b722ff5116ff79c0dbc68 -- want to hard refresh and try one more time?

**Comment by mkosowsk** [comment]
@owocki sure bet. I hard refreshed and even restarted to try to make sure 😂one possible confounding factor is that I was switching between networks on Metamask but I am most certainly on the Main Ethereum Network

**Comment by mkosowsk** [comment]
Success! Thanks for taking a look. Our friend is now 0.0001 ETH richer

I swear I hard refreshed earlier, maybe I did it before the deploy went live? Or perhaps the classic PEBCAK (problem exists between chair and keyboard 😂)

Thanks!

**Comment by owocki** [comment]
> I swear I hard refreshed earlier, maybe I did it before the deploy went live? Or perhaps the classic PEBCAK (problem exists between chair and keyboard 😂)

i made two seperate fixes.. looks like the second one is the one that worked

**Comment by darkdarkdragon** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__This issue now has a funding of 0.001 ETH (0.69 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/776/568).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
