### ISSUE TITLE
Unable to edit grant. Please try again

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#8446]
https://gitcoin.co/grants/1591/science-of-the-future-the-100-years-forward-plan

SAVE CHANGES

Unable to edit grant. Please try again

**Comment by Kweiss** [comment]
This is resolved.

**Comment by vporton** [comment]
> This is resolved. the grant was missing an address throwing a 400 error (related to zCash). I updated this on the backend and you should be good to go.

It still does not work with the same error. The attempt to clear browser cache does not help.

**Comment by vporton** [comment]
@Kweiss By the way, I see no way to add a zCash wallet.
